{{ $fullname :=  include "gateway.fullname" . }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    role: gateway
    type: kubernetes-events
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $fullname }}
        role: gateway
        type: kuberentes-events
    spec:
      serviceAccountName: {{ $fullname }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry }}/{{ .Values.name }}:{{ default .Chart.AppVersion .Values.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.pullPolicy }}
        env:
          - name: GATEWAY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GATEWAY_CONFIG
            value: "/etc/brigade-k8s-gateway/filters.json"
        volumeMounts:
          - name: filters-config
            mountPath: /etc/brigade-k8s-gateway
      volumes:
        - name: filters-config
          configMap:
            name: {{ $fullname }}
